apiVersion: batch/v1
kind: Job
metadata:
  name:  "cinder-db-sync"
  namespace: {{ .Release.Namespace | quote }}
spec:
  template:
    spec:
      activeDeadlineSeconds: 200
      containers:
      - env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_SERVICE_NAME
          value: db-sync
        - name: KOLLA_BOOTSTRAP
        image: {{ template "cinder.api.image" . }}
        imagePullPolicy: IfNotPresent
        name: cinder-db-sync
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /var/lib/kolla/config_files
          name: configdir
        - mountPath: /var/log/kolla/cinder
          name: logdir
        - mountPath: /var/lib/kolla/config_files/config.json
          name: cinder-etc
          subPath: db-sync.json
        - mountPath: /tmp/db-sync.sh
          name: cinder-bin
          subPath: db-sync.sh
        - mountPath: /var/lib/kolla/config_files/cinder.conf
          name: cinder-etc
          subPath: cinder.conf
        - mountPath: /var/lib/cinder/
          name: cinder-data
          mountPropagation: Bidirectional
        securityContext:
          runAsUser: 0
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
      dnsPolicy: ClusterFirst
      initContainers:
      - name: init
        image: {{ template "kubernetes.entrypoint.image" . }}
        imagePullPolicy: IfNotPresent
        command:
        - kubernetes-entrypoint
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      restartPolicy: OnFailure
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - emptyDir: {}
        name: configdir
      - emptyDir: {}
        name: logdir
      - configMap:
          defaultMode: 493
          name: cinder-bin
        name: cinder-bin
      - configMap:
          defaultMode: 420
          name: cinder-etc
        name: cinder-etc
      - hostPath:
          path: /var/lib/cinder/
        name: cinder-data
