# This YAML file contains nginx & csi cinder driver objects,
# which are necessary to run nginx with csi cinder driver.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-metal-csi-local
provisioner: cinder.metal.csi
parameters:
  type: local

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinder-pvc-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: cinder-metal-csi-local

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-local
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/html
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: cinder-pvc-local
        readOnly: false
