kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "cinder-metal-csi.name" . }}-controllerplugin
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controllerPlugin.replicas }}
  selector:
    matchLabels:
      app: {{ include "cinder-metal-csi.name" . }}
      component: {{ .Values.controllerPlugin.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cinder-metal-csi.name" . }}
        component: {{ .Values.controllerPlugin.name }}
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Values.controllerPlugin.serviceAccountName }}
      containers:
        - name: csi-attacher
          image: "{{ .Values.image.attacher.repository }}:{{ .Values.image.attacher.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-v={{ .Values.logVerbosityLevel }}"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-provisioner
          image: "{{ .Values.image.provisioner.repository }}:{{ .Values.image.provisioner.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-v={{ .Values.logVerbosityLevel }}"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
            - "--leader-election=true"
            - "--default-fstype=ext4"
            - "--extra-create-metadata"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-snapshotter
          image: "{{ .Values.image.snapshotter.repository }}:{{ .Values.image.snapshotter.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-v={{ .Values.logVerbosityLevel }}"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - name: csi-resizer
          image: "{{ .Values.image.resizer.repository }}:{{ .Values.image.resizer.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-v={{ .Values.logVerbosityLevel }}"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=3m"
            - "--handle-volume-inuse-error=false"
            - "--leader-election=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: liveness-probe
          image: "{{ .Values.image.livenessprobe.repository }}:{{ .Values.image.livenessprobe.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-v={{ .Values.logVerbosityLevel }}"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
        - name: cinder-metal-csi
          image: "{{ .Values.image.cinderMetalCSI.repository }}:{{ .Values.image.cinderMetalCSI.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /bin/cinder-metal-csi
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloud-conf=$(CLOUD_CONFIG)"
            - "--node-id=$(NODE_ID)"
            - "--v=3"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: CLOUD_CONFIG
              value: /etc/cloud/cloud.conf
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: cloud-config
              mountPath: /etc/cloud/cloud.conf
              subPath: cloud.conf
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: cloud-config
          configMap:
            name: {{ .Release.Name }}-configmap
            defaultMode: 0755
