version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            free -h
            df -h
