apiVersion: v1
data:
  ceph.conf: |
    [global]
    mon_host = 10.111.43.63:6789
    [client.cinder]
    keyring = /etc/ceph/keyring
  iscsi.json: |
    {
      "command": "iscsid -d 8 -f",
      "config_files": []
    }
kind: ConfigMap
metadata:
  name: cinder-cm
  namespace: kube-system
