# This YAML file contains secret objects,
# which are necessary to run csi cinder plugin.

kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud.conf: W0dsb2JhbF0KdXNlcm5hbWUgPSBhZG1pbgpwYXNzd29yZCA9IG8yRGtnYmN3RFoKdXNlci1kb21haW4tbmFtZSA9IGRlZmF1bHQKcHJvamVjdC1kb21haW4tbmFtZSA9IGRlZmF1bHQKcHJvamVjdC1uYW1lID0gYWRtaW4KdGVuYW50LW5hbWUgPSBhZG1pbgphdXRoLXVybCA9IGh0dHA6Ly9rZXlzdG9uZS1hcGkuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo1MDAwL3YzCnJlZ2lvbiA9IFJlZ2lvbk9uZQplbmRwb2ludC10eXBlID0gaW50ZXJuYWwKCltCbG9ja1N0b3JhZ2VdCmF1dGgtc3RyYXRlZ3kgPSBrZXlzdG9uZQpjaW5kZXItbGlzdGVuLWFkZHIgPSBodHRwOi8vY2luZGVyLWFwaS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjg3NzYvdjMKbm9kZS12b2x1bWUtYXR0YWNoLWxpbWl0ID0gMTEwCmx2bS12b2x1bWUtdHlwZSA9IGx2bQpjZXBoLXZvbHVtZS10eXBlID0gcmJkCmxvY2FsLXZvbHVtZS10eXBlID0gbG9jYWwK
