apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cinder-metal-csi-lvm
  namespace: kube-system
provisioner: cinder.metal.csi
allowVolumeExpansion: true
parameters:
  cinderVolumeType: lvm
