apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-demo
spec:
  volumeSnapshotClassName: cinder-metal-csi-snapshot
  source:
    persistentVolumeClaimName: cinder-pvc-lvm
