apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace:  {{ .Release.Namespace | quote }}
  labels: {{- include "rabbitmq.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: epmd
  - name: dist
    port: 25672
    protocol: TCP
    targetPort: dist
  - name: http-stats
    port: 15672
    protocol: TCP
    targetPort: stats
  selector: {{- include "rabbitmq.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: "rabbitmq"
  
