---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cinder-pvc-lvm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cinder-metal-csi-lvm
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lvm
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/www/html
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: cinder-pvc-lvm
        readOnly: false
