name: Lint Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      # https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md
      - name: Run chart-testing (lint)
        run: ct lint --target-branch=${GITHUB_BASE_REF} --check-version-increment=false
